name: Build APK Engine

on:
  repository_dispatch:
    types: [build-app]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Receive Data From Render
        run: |
          echo "Render server ne App banane ka order diya hai!"
          echo "App Name: ${{ github.event.client_payload.appName }}"
          echo "Website URL: ${{ github.event.client_payload.appUrl }}"
